services:
  mi-proyecto-devops:
    image: localhost:8082/mi-proyecto-devops
    restart: always
    ports:
      - "3000:3000"
    environment:
      AMBIENTE=development
      API_KEY=/run/secrets/API_KEY
secrets:
  api_key:
    file: api_key.txt