pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                sh sudo docker { image 'node:20.11.1-alpine3.19' }
            }
            stages {
                stage('checkout') {
                    steps {
                        echo "hola mundo"
                    }

                }
            }
        }
    }
}
