pipeline {
    agent any
    stages {
        stage('Instalar dependencias') {
            steps {
                echo 'Instalando dependencias'
                sh 'npm install'
            }
        }
        stage('Pruebas unitarias') {
            steps {
                echo 'Ejecutando pruebas unitarias'
                sh 'npm run test'
            }
        }
        stage('Traspilar') {
            steps {
                echo 'Traspilando proyecto'
                sh 'npm run build'
            }
        }
    }
}